body{
    background-color:grey;
}
.container h3{
    color:white;
    float:left;
    padding:10px;
    background-color:#2E0505
    height:10px;
    text-align:center;
    font-family:transit;
}
.section{
  color:yellow;
    float:left;
    padding:10px;
    background-color:#2E0505
    height:10px;
    text-align:center;
    font-family:transit;  
}